name: Test

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.2'

      - name: Update system dependencies
        run: |
          sudo apt-get update
          # Install libraries for canvas and image processing
          # These are needed to build the canvas module with proper native bindings
          sudo apt-get install -y \
            build-essential \
            libcairo2-dev \
            libpango1.0-dev \
            libjpeg-dev \
            libgif-dev \
            librsvg2-dev \
            libpixman-1-dev \
            libjpeg-turbo8-dev \
            libpng-dev
          
          # Show installed library versions for debugging
          echo "Installed library versions:"
          pkg-config --modversion cairo || echo "cairo not found"
          pkg-config --modversion pango || echo "pango not found"
          dpkg -l | grep libjpeg || echo "libjpeg packages not listed"

      - name: Install dependencies
        run: |
          # Clean install to ensure native modules are built with updated system libraries
          rm -rf node_modules
          bun install --force

      - name: Build executable
        run: bun run build

      - name: Test executable
        run: |
          ./mineflare --version
          ./mineflare --help
          ./mineflare server --help

      - name: Check file size
        run: |
          ls -lh mineflare
          size=$(stat -c%s mineflare)
          echo "Executable size: $((size/1024/1024)) MB"
          if [ $size -gt 536870912 ]; then
            echo "Warning: Executable larger than 512MB"
            exit 1
          fi